### ISSUE TITLE
求兼容最新的火狐

### ISSUE THREAD

**Issue by fowse42** [leiqin/zdic#1]
rt
最新的Firefox58不能使用，希望作者抽空能更新一下。

**Comment by leiqin** [comment]
已更新，请尝试。
汉典尚不支持 HTTPS，新版的 WebExtensions API 插件无法从 HTTPS 页面访问 HTTP 页面（mix content error），添加了一个右键菜单（可禁用），可以在新标签中打开汉典查找。

**Comment by fowse42** [comment]
赞，还更新了Chrome的版本，感谢！
